name: Build & Test

on:
  push:

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Can Build
        run: npm run build

      - name: Generate Codes
        run: npm run generate

      - name: Run typecheck
        run: npm run typecheck

      - name: Run lint
        run: npm run lint
